### PR TITLE
fixing headline border

### PR DESCRIPTION
**Pull request by gpedro**
ordered by
- original
- current
- this pr

diffs

### CODE REVIEW

**Comment by eklundchristopher** [comment]
I'm more than happy to merge this, but before I do, what browser and OS do you use?

This is what I see (top being the current one, and bottom being from this PR):

headline

PS. Note that the screenshots are taken on my 4K monitor, but it's the same on my 1080p monitors.

**Comment by gpedro** [comment]
wow, what difference!!! i'll check using another browsers. w8.
-- edited
ahm! I really don't understand. Safari and Chrome use the same engine and chrome works and the other doesn't

-- edited
i'm using Safari @ OS X. I think the cause of the problem is the retina display

@eklundchristopher

**Comment by eklundchristopher** [comment]
Ah, yes. Safari does seem to have a much thinner border. Nice catch. Maybe see if you can find a safari only CSS selector and add it there, and then I'll be happy to merge this! :-)

**Comment by gpedro** [comment]
i see the border only at max zoom
captura de tela 2016-07-25 as 22 15 13

**Comment by eklundchristopher** [comment]
You're right. Taking a second look I see no border whatsoever. Me being tired and looking at my 4K monitor it kinda looked like a thin border, but it is as you say, there's none, unless maximum zoom.

If you find a Safari only CSS selector for it, please do submit it. If not, I'll look into this tomorrow and sort it out.

**Comment by gpedro** [comment]
if we think big, we can create a simple solution to these css features. just add the browser name in the body tag can help solve these little things.

**Comment by eklundchristopher** [comment]
Yeah, that's another way of doing it I guess. I've been contemplating abandoning the project because of lack of motivation/interest in TIbia related matters. Currently looking for someone to take over, or help out, if it's to any interest to you. :-)

**Pull request closed without merging**
